### ISSUE TITLE
flowforge/file-server:latest not found

### ISSUE THREAD

**Issue by pvandendool** [flowforge/docker-compose#54]
### Current Behavior

Downloaded the last release, 1.1.0 and trying to start it with docker compose.

When i use "sudo docker compose -p flowforge up -d" i get the following error.
```
Error response from daemon: manifest for flowforge/file-server:latest not found: manifest unknown: manifest unknown
```

### Environment

- FlowForge version: 1.1.0
- Node.js version:
- npm version:
- Platform/OS: Debian
- Browser:

**Comment by hardillb** [comment]
Thanks for reporting this.

The quick fix is to add the 1.1.0 tag to the docker-compose file

```
  file-server:
    image: "flowforge/file-server:1.1.0"
    networks:
      - flowforge
    restart: always
```
